export type DefaultPlanExercise = {
  exerciseName: string;
  sets: number;
  reps: string;
  tempo: string;
  restSeconds: number;
  targetRPE: string;
  cues: string;
  supersetGroup: string | null;
  exerciseType: string;
};

export type DefaultWorkoutDay = {
  dayOfWeek: number;
  sessionName: string;
  exercises: DefaultPlanExercise[];
};

export const DEFAULT_WORKOUT_PLAN_VERSION = "4-day-beginner-machine-circuit-v2";

export const DEFAULT_WORKOUT_PLAN_NOTES = [
  "Beginner restart block for a 311 lb sedentary male returning to training.",
  "Run A/B/C circuit blocks as the listed pairings or sequences for each day.",
  "Use machine, seated, cable, and bench-supported exercises to keep setup simple and stable.",
  "Use RPE 6-7 and leave 2-4 reps in reserve on every working set.",
  "Weeks 1-2 may use optional 2-round mode: complete two rounds per block instead of all listed sets.",
  "Rest only after each pair or full circuit, not between paired exercises unless needed for safety.",
];

const PLAN_CUE_PREFIX =
  "Beginner machine-supported block: move smoothly, stop 2-4 reps before failure, and use optional 2-round mode in weeks 1-2. ";

export const DEFAULT_WORKOUT_PLAN: DefaultWorkoutDay[] = [
  {
    dayOfWeek: 1,
    sessionName: "Upper A - Machine Push/Pull Foundation",
    exercises: [
      {
        exerciseName: "Ramp-Up: Treadmill Walk + Light Face Pull",
        sets: 1,
        reps: "5 min walk + 12 light reps",
        tempo: "easy",
        restSeconds: 60,
        targetRPE: "3-4",
        cues: "Nasal-breathing pace on the treadmill, then use a very light rope face pull to warm the upper back before the circuit blocks.",
        supersetGroup: null,
        exerciseType: "WARMUP",
      },
      {
        exerciseName: "A1 Machine Chest Press",
        sets: 3,
        reps: "8-12",
        tempo: "3-1-1",
        restSeconds: 90,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Set the handles around mid-chest, keep the back against the pad, press smoothly, and rest 90 seconds after A2.`,
        supersetGroup: "A",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "A2 Chest-Supported Row Machine",
        sets: 3,
        reps: "8-12",
        tempo: "2-1-2",
        restSeconds: 90,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Keep the chest on the pad, pull elbows toward ribs, pause one second, then lower under control before resting after the pair.`,
        supersetGroup: "A",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "B1 Neutral-Grip Lat Pulldown",
        sets: 3,
        reps: "8-12",
        tempo: "2-1-2",
        restSeconds: 90,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Pull handles toward the upper chest, keep ribs down, and let the shoulder blades glide upward on the return.`,
        supersetGroup: "B",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "B2 Machine Shoulder Press",
        sets: 3,
        reps: "8-10",
        tempo: "2-1-2",
        restSeconds: 90,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Use the seat and back pad for support, press in a pain-free path, and stop short of any shoulder pinch before resting after B2.`,
        supersetGroup: "B",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "C1 Rope Triceps Pressdown",
        sets: 2,
        reps: "10-15",
        tempo: "2-1-2",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Pin elbows to your sides, finish without leaning over the cable, and move directly to C2.`,
        supersetGroup: "C",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "C2 Cable Curl",
        sets: 2,
        reps: "10-15",
        tempo: "2-1-2",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Keep shoulders quiet, curl without swinging, and use a load that stays smooth through the full range.`,
        supersetGroup: "C",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "C3 Face Pull",
        sets: 2,
        reps: "12-15",
        tempo: "2-1-2",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Pull the rope toward eye level with elbows high, keep the neck relaxed, then rest 120 seconds after the circuit.`,
        supersetGroup: "C",
        exerciseType: "WORKING",
      },
    ],
  },
  {
    dayOfWeek: 2,
    sessionName: "Lower A - Machine Lower Body Foundation",
    exercises: [
      {
        exerciseName: "Ramp-Up: Recumbent Bike + Leg Press Rehearsal",
        sets: 1,
        reps: "5 min bike + 8 light reps",
        tempo: "easy",
        restSeconds: 60,
        targetRPE: "3-4",
        cues: "Warm the knees and hips gently, then use a very light leg press set to practice foot position and range before the first block.",
        supersetGroup: null,
        exerciseType: "WARMUP",
      },
      {
        exerciseName: "A1 Leg Press",
        sets: 3,
        reps: "8-12",
        tempo: "3-1-1",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Use a comfortable stance, keep the low back against the pad, and stop depth before the pelvis tucks; rest 120 seconds after A2.`,
        supersetGroup: "A",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "A2 Seated Hamstring Curl",
        sets: 3,
        reps: "10-15",
        tempo: "2-1-2",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Curl through a pain-free range, pause gently, and return slowly before resting after the pair.`,
        supersetGroup: "A",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "B1 Walking Lunges",
        sets: 2,
        reps: "8-12 steps per leg",
        tempo: "controlled pace",
        restSeconds: 90,
        targetRPE: "6-7",
        cues: "Use bodyweight first, take controlled steps with a tall torso, and hold dumbbells only when stable and pain-free; rest 90 seconds after the set or after the circuit block.",
        supersetGroup: "B",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "C1 Leg Extension",
        sets: 2,
        reps: "10-15",
        tempo: "2-1-2",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Lift under control, pause briefly near the top, and lower without letting the stack slam.`,
        supersetGroup: "C",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "C2 Seated Calf Raise",
        sets: 2,
        reps: "10-15",
        tempo: "2-1-2",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Move through a comfortable ankle range, pause at the top, and lower slowly before C3.`,
        supersetGroup: "C",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "C3 Hip Abduction Machine",
        sets: 2,
        reps: "12-15",
        tempo: "2-1-2",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Control the outside hip work, avoid bouncing at end range, then rest 120 seconds after the circuit.`,
        supersetGroup: "C",
        exerciseType: "WORKING",
      },
    ],
  },
  {
    dayOfWeek: 4,
    sessionName: "Upper B - Machine Back/Shoulder Emphasis",
    exercises: [
      {
        exerciseName: "Ramp-Up: Arm Bike + Light Pulldown",
        sets: 1,
        reps: "5 min arm bike + 10 light reps",
        tempo: "easy",
        restSeconds: 60,
        targetRPE: "3-4",
        cues: "Keep breathing calm on the arm bike, then use a very light pulldown set to groove shoulder blade motion before the first block.",
        supersetGroup: null,
        exerciseType: "WARMUP",
      },
      {
        exerciseName: "A1 Incline Machine Press",
        sets: 3,
        reps: "8-12",
        tempo: "3-1-1",
        restSeconds: 90,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Set the seat so the handles track upper chest, keep the back supported, and rest 90 seconds after A2.`,
        supersetGroup: "A",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "A2 Seated Cable Row",
        sets: 3,
        reps: "8-12",
        tempo: "2-1-2",
        restSeconds: 90,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Sit tall with feet planted, row handles to the lower ribs, pause, and return under control before resting after the pair.`,
        supersetGroup: "A",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "B1 Lat Pulldown Variation",
        sets: 3,
        reps: "8-12",
        tempo: "2-1-2",
        restSeconds: 90,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Use a grip that feels natural, pull to the upper chest, and keep the ribs stacked over the pelvis.`,
        supersetGroup: "B",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "B2 Machine Lateral Raise",
        sets: 3,
        reps: "12-15",
        tempo: "2-1-2",
        restSeconds: 90,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Use the pads for support, raise only through a comfortable range, and keep the neck relaxed before resting after B2.`,
        supersetGroup: "B",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "C1 Reverse Pec Deck",
        sets: 2,
        reps: "12-15",
        tempo: "2-1-2",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Lead with elbows, keep the chest supported, and move directly to C2.`,
        supersetGroup: "C",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "C2 Rope Triceps Pressdown",
        sets: 2,
        reps: "10-15",
        tempo: "2-1-2",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Keep elbows pinned, finish with control, and avoid using bodyweight to move the stack.`,
        supersetGroup: "C",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "C3 Cable Curl",
        sets: 2,
        reps: "10-15",
        tempo: "2-1-2",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Curl smoothly without swinging, keep shoulders quiet, then rest 120 seconds after the circuit.`,
        supersetGroup: "C",
        exerciseType: "WORKING",
      },
    ],
  },
  {
    dayOfWeek: 5,
    sessionName: "Lower B - Machine Posterior Chain",
    exercises: [
      {
        exerciseName: "Ramp-Up: Recumbent Bike + Hamstring Curl Rehearsal",
        sets: 1,
        reps: "5 min bike + 10 light reps",
        tempo: "easy",
        restSeconds: 60,
        targetRPE: "3-4",
        cues: "Warm up with easy cycling, then use a very light hamstring curl set to find a comfortable knee range before the circuit blocks.",
        supersetGroup: null,
        exerciseType: "WARMUP",
      },
      {
        exerciseName: "A1 Hack Squat Machine",
        sets: 3,
        reps: "8-12",
        tempo: "3-1-1",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Keep the back on the pad, use a controlled depth, drive through the whole foot, and rest 120 seconds after A2.`,
        supersetGroup: "A",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "A2 Lying Hamstring Curl",
        sets: 3,
        reps: "10-15",
        tempo: "2-1-2",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Keep hips heavy on the pad, curl smoothly, pause gently, and return slowly before resting after the pair.`,
        supersetGroup: "A",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "B1 Glute Kickback Machine",
        sets: 3,
        reps: "8-12/side",
        tempo: "2-1-2",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Set the pad so the hip drives straight back, pause without arching the low back, and use an easy setup load.`,
        supersetGroup: "B",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "B2 Back Extension Machine",
        sets: 3,
        reps: "10-12",
        tempo: "2-1-2",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Move through the hips with a neutral spine, stop before low-back strain, and rest after B2.`,
        supersetGroup: "B",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "C1 Leg Extension",
        sets: 2,
        reps: "10-15",
        tempo: "2-1-2",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Use a smooth squeeze at the top and control the lowering phase without bouncing.`,
        supersetGroup: "C",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "C2 Leg Press Calf Press",
        sets: 2,
        reps: "12-20",
        tempo: "2-1-2",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Use the leg press for calf work, keep knees softly bent, and move through a comfortable ankle range before C3.`,
        supersetGroup: "C",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "C3 Hip Adduction Machine",
        sets: 2,
        reps: "12-15",
        tempo: "2-1-2",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Control the inner thigh work, avoid bouncing at end range, then rest 120 seconds after the circuit.`,
        supersetGroup: "C",
        exerciseType: "WORKING",
      },
    ],
  },
];

export const DEFAULT_WEEKLY_RHYTHM = [
  "Monday: Upper A - Machine Push/Pull Foundation",
  "Tuesday: Lower A - Machine Lower Body Foundation",
  "Wednesday: Mobility / Recovery",
  "Thursday: Upper B - Machine Back/Shoulder Emphasis",
  "Friday: Lower B - Machine Posterior Chain",
  "Saturday: Mobility / Recovery",
  "Sunday: Complete Rest",
];
