export type DefaultPlanExercise = {
  exerciseName: string;
  sets: number;
  reps: string;
  tempo: string;
  restSeconds: number;
  targetRPE: string;
  cues: string;
  supersetGroup: string | null;
  exerciseType: string;
};

export type DefaultWorkoutDay = {
  dayOfWeek: number;
  sessionName: string;
  exercises: DefaultPlanExercise[];
};

export const DEFAULT_WORKOUT_PLAN_VERSION = "4-day-beginner-circuit-v1";

export const DEFAULT_WORKOUT_PLAN_NOTES = [
  "Beginner restart block for a 311 lb sedentary male returning to training.",
  "Run A/B/C circuit blocks as A1/A2, B1/B2, and C1/C2/C3 pairings.",
  "Use RPE 6-7 and leave 2-4 reps in reserve on every working set.",
  "Weeks 1-2 may use optional 2-round mode: complete two rounds per block instead of all listed sets.",
  "Rest only after each pair or full circuit, not between paired exercises unless needed for safety.",
];

const PLAN_CUE_PREFIX =
  "Beginner restart block: move smoothly, stop 2-4 reps before failure, and use optional 2-round mode in weeks 1-2. ";

export const DEFAULT_WORKOUT_PLAN: DefaultWorkoutDay[] = [
  {
    dayOfWeek: 1,
    sessionName: "Upper A — Push/Pull Foundation",
    exercises: [
      {
        exerciseName: "Ramp-Up: Treadmill Walk + Band Pull-Apart",
        sets: 1,
        reps: "5 min walk + 12 pull-aparts",
        tempo: "easy",
        restSeconds: 60,
        targetRPE: "3-4",
        cues: "Nasal-breathing pace on the treadmill, then light band pull-aparts to open the chest before the circuit blocks.",
        supersetGroup: null,
        exerciseType: "WARMUP",
      },
      {
        exerciseName: "A1 Incline Push-Up",
        sets: 3,
        reps: "8-10",
        tempo: "3-1-1",
        restSeconds: 90,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Use a bench, Smith bar, or wall height that lets every rep stay crisp; rest 90 seconds after A2.`,
        supersetGroup: "A",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "A2 Chest-Supported Dumbbell Row",
        sets: 3,
        reps: "10-12",
        tempo: "2-1-2",
        restSeconds: 90,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Keep the chest on the pad, pull elbows toward ribs, pause one second, then lower under control before resting after the pair.`,
        supersetGroup: "A",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "B1 Seated Dumbbell Shoulder Press",
        sets: 3,
        reps: "8-10",
        tempo: "2-1-2",
        restSeconds: 90,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Press from a supported seat without arching; stop short of any shoulder pinch and rest after B2.`,
        supersetGroup: "B",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "B2 Neutral-Grip Lat Pulldown",
        sets: 3,
        reps: "10-12",
        tempo: "2-1-2",
        restSeconds: 90,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Pull handles toward the upper chest, keep ribs down, and let the shoulder blades glide upward on the return.`,
        supersetGroup: "B",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "C1 Cable Face Pull",
        sets: 2,
        reps: "12-15",
        tempo: "2-1-2",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Start the three-move C circuit with light posture work; rest 120 seconds after C3.`,
        supersetGroup: "C",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "C2 Cable Triceps Pressdown",
        sets: 2,
        reps: "10-12",
        tempo: "2-1-2",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Pin elbows to your sides and finish each rep without leaning your torso over the cable.`,
        supersetGroup: "C",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "C3 Standing Dumbbell Curl",
        sets: 2,
        reps: "10-12",
        tempo: "2-1-2",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Stand tall, avoid swinging, and complete the circuit before taking the controlled rest.`,
        supersetGroup: "C",
        exerciseType: "WORKING",
      },
    ],
  },
  {
    dayOfWeek: 2,
    sessionName: "Lower A — Stable Lower Body",
    exercises: [
      {
        exerciseName: "Ramp-Up: Recumbent Bike + Sit-to-Stand",
        sets: 1,
        reps: "5 min bike + 8 sit-to-stands",
        tempo: "easy",
        restSeconds: 60,
        targetRPE: "3-4",
        cues: "Warm the knees and hips gently, then practice standing from a box or bench with even foot pressure.",
        supersetGroup: null,
        exerciseType: "WARMUP",
      },
      {
        exerciseName: "A1 Box Squat to Bench",
        sets: 3,
        reps: "8-10",
        tempo: "3-1-1",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Sit back to a stable box or bench, keep the whole foot down, and rest 120 seconds after A2.`,
        supersetGroup: "A",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "A2 Standing Calf Raise Support Hold",
        sets: 3,
        reps: "10-12",
        tempo: "2-1-2",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Hold a rail or machine for balance, rise smoothly, pause at the top, and lower without bouncing.`,
        supersetGroup: "A",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "B1 Leg Press",
        sets: 3,
        reps: "10-12",
        tempo: "3-1-1",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Use a comfortable stance, keep the low back against the pad, and stop depth before the pelvis tucks.`,
        supersetGroup: "B",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "B2 Seated Leg Curl",
        sets: 3,
        reps: "10-12",
        tempo: "2-1-2",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Curl through a pain-free range, pause gently, and return slowly before resting after the pair.`,
        supersetGroup: "B",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "C1 Step-Up to Low Box",
        sets: 2,
        reps: "6-8/side",
        tempo: "controlled",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Use a low step and support as needed; this is balance practice, not a max-effort lift.`,
        supersetGroup: "C",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "C2 Pallof Press",
        sets: 2,
        reps: "8-10/side",
        tempo: "2-1-2",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Brace the trunk and press the cable or band straight out without rotating.`,
        supersetGroup: "C",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "C3 Farmer Carry",
        sets: 2,
        reps: "30-45 sec",
        tempo: "steady walk",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Carry light dumbbells with tall posture; stop before grip or breathing forces compensation, then rest after the circuit.`,
        supersetGroup: "C",
        exerciseType: "WORKING",
      },
    ],
  },
  {
    dayOfWeek: 4,
    sessionName: "Upper B — Back/Shoulder Emphasis",
    exercises: [
      {
        exerciseName: "Ramp-Up: Arm Bike + Wall Slides",
        sets: 1,
        reps: "5 min arm bike + 10 wall slides",
        tempo: "easy",
        restSeconds: 60,
        targetRPE: "3-4",
        cues: "Keep breathing calm and use the wall slides to find pain-free overhead range before the first block.",
        supersetGroup: null,
        exerciseType: "WARMUP",
      },
      {
        exerciseName: "A1 Lat Pulldown",
        sets: 3,
        reps: "10-12",
        tempo: "2-1-2",
        restSeconds: 90,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Pull to the upper chest with shoulders down and rest 90 seconds after A2.`,
        supersetGroup: "A",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "A2 Machine Chest Press (Light Technique)",
        sets: 3,
        reps: "8-10",
        tempo: "3-1-1",
        restSeconds: 90,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}This is light technique work, not the old chest-press priority day; press smoothly and stop with reps in reserve.`,
        supersetGroup: "A",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "B1 Supported One-Arm Cable Row",
        sets: 3,
        reps: "10/side",
        tempo: "2-1-2",
        restSeconds: 90,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Brace with the free hand, row without twisting, and rest after B2.`,
        supersetGroup: "B",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "B2 Dumbbell Lateral Raise",
        sets: 3,
        reps: "10-12",
        tempo: "2-1-2",
        restSeconds: 90,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Use light dumbbells, raise to a comfortable height, and keep traps relaxed.`,
        supersetGroup: "B",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "C1 Rear Delt Fly Machine",
        sets: 2,
        reps: "12-15",
        tempo: "2-1-2",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Lead with elbows and keep the neck relaxed through the first station of the C circuit.`,
        supersetGroup: "C",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "C2 Incline Dumbbell Press (Low Incline)",
        sets: 2,
        reps: "8-10",
        tempo: "3-1-1",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Use a low incline and light load; this accessory press replaces the old heavy incline prescription.`,
        supersetGroup: "C",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "C3 Dead Bug",
        sets: 2,
        reps: "6-8/side",
        tempo: "slow",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Keep the low back gently pinned down and breathe out as the arm and leg extend, then rest after the circuit.`,
        supersetGroup: "C",
        exerciseType: "WORKING",
      },
    ],
  },
  {
    dayOfWeek: 5,
    sessionName: "Lower B — Hips/Posterior Chain",
    exercises: [
      {
        exerciseName: "Ramp-Up: Treadmill Walk + Hip Hinge Drill",
        sets: 1,
        reps: "5 min walk + 10 hinges",
        tempo: "easy",
        restSeconds: 60,
        targetRPE: "3-4",
        cues: "Walk until joints feel warm, then practice pushing hips back with hands on ribs and pelvis stacked.",
        supersetGroup: null,
        exerciseType: "WARMUP",
      },
      {
        exerciseName: "A1 Dumbbell Romanian Deadlift",
        sets: 3,
        reps: "8-10",
        tempo: "3-1-1",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Use light dumbbells, hinge only as far as the back stays neutral, and rest 120 seconds after A2.`,
        supersetGroup: "A",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "A2 Glute Bridge",
        sets: 3,
        reps: "10-12",
        tempo: "2-1-2",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Drive through heels, pause at the top, and avoid turning the bridge into a low-back arch.`,
        supersetGroup: "A",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "B1 Seated Leg Curl",
        sets: 3,
        reps: "10-12",
        tempo: "2-1-2",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Keep hips down, squeeze hamstrings, and rest after B2.`,
        supersetGroup: "B",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "B2 Cable Pull-Through",
        sets: 3,
        reps: "10-12",
        tempo: "2-1-2",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Face away from a low cable, hinge back, then stand tall by squeezing glutes without leaning back.`,
        supersetGroup: "B",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "C1 Hip Abduction Machine",
        sets: 2,
        reps: "12-15",
        tempo: "2-1-2",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Control the outside hip work and avoid bouncing at end range.`,
        supersetGroup: "C",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "C2 Sled Push or Treadmill Incline Walk",
        sets: 2,
        reps: "45-60 sec",
        tempo: "steady",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Choose sled if available or a gentle incline walk if not; breathing should stay controlled.`,
        supersetGroup: "C",
        exerciseType: "WORKING",
      },
      {
        exerciseName: "C3 Side Plank from Knees",
        sets: 2,
        reps: "15-25 sec/side",
        tempo: "steady hold",
        restSeconds: 120,
        targetRPE: "6-7",
        cues: `${PLAN_CUE_PREFIX}Make a straight line from shoulder to knee, breathe, and stop before form breaks; rest after the circuit.`,
        supersetGroup: "C",
        exerciseType: "WORKING",
      },
    ],
  },
];

export const DEFAULT_WEEKLY_RHYTHM = [
  "Monday: Upper A — Push/Pull Foundation",
  "Tuesday: Lower A — Stable Lower Body",
  "Wednesday: Mobility / Recovery",
  "Thursday: Upper B — Back/Shoulder Emphasis",
  "Friday: Lower B — Hips/Posterior Chain",
  "Saturday: Mobility / Recovery",
  "Sunday: Complete Rest",
];
